// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaqZKanIo9-KMGPNlp4Url6X4jqFJXo-0',
    appId: '1:320217009333:web:77f839ac33ff7ce99802fc',
    messagingSenderId: '320217009333',
    projectId: 'majdi-ad817',
    authDomain: 'majdi-ad817.firebaseapp.com',
    storageBucket: 'majdi-ad817.appspot.com',
    measurementId: 'G-MS9W26MELX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZtkMlSJ8Cdk4_juLwy1Qcguo7tx3Hx0',
    appId: '1:320217009333:android:01347902302483589802fc',
    messagingSenderId: '320217009333',
    projectId: 'majdi-ad817',
    storageBucket: 'majdi-ad817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMw1sWzOFqWdlCO-v-WzwX_NWVvF2Cq1U',
    appId: '1:320217009333:ios:751640328a4089a89802fc',
    messagingSenderId: '320217009333',
    projectId: 'majdi-ad817',
    storageBucket: 'majdi-ad817.appspot.com',
    iosBundleId: 'com.example.p1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMw1sWzOFqWdlCO-v-WzwX_NWVvF2Cq1U',
    appId: '1:320217009333:ios:751640328a4089a89802fc',
    messagingSenderId: '320217009333',
    projectId: 'majdi-ad817',
    storageBucket: 'majdi-ad817.appspot.com',
    iosBundleId: 'com.example.p1',
  );
}
